env:
  browser: true
  es2020: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - "@typescript-eslint"
  - jest-dom
  - jsx-a11y
  - prettier
  - react
  - react-hooks
  - testing-library
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest-dom/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
  - plugin:react/jsx-runtime
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:testing-library/dom
rules:
  linebreak-style:
    - error
    - unix
  react/display-name: off
  react/react-in-jsx-scope: off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/no-var-requires": off
  prettier/prettier: error
settings:
  react:
    version: detect
